#! /bin/sh

# 绑定Fn键调整声音
xfce4-volumed-pulse &
# 绑定Fn键调整亮度
xfce4-power-manager &
# 全局窗口快捷键
pgrep -x sxhkd > /dev/null || sxhkd &
# 鼠标光标在空窗口仍然是箭头而不是X
xsetroot -cursor_name left_ptr
# Polybar
~/.config/polybar/launch.sh
# Fcitx5
fcitx5 &
# Picom窗口合成器
picom --experimental-backends --config ~/.config/picom/picom-yaoc.conf &
# 通知服务
dunst &
# 剪贴板服务
/usr/lib/gpaste/gpaste-daemon &

#工作区
bspc monitor -d 一 二 三 四 五 六 七 八 九 十

#窗口边框设置
bspc config border_width         4

#窗口间隔
bspc config window_gap           7

bspc config split_ratio          0.52
#单窗口模式设置
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#边框颜色
bspc config focused_border_color "#5E81AC"
bspc config normal_border_color "#4C566A"

#只有一个窗口时开启单窗口模式
bspc config single_monocle false
#bspc config focus_follows_pointer true
bspc rule -a Thunar state=floating

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Gedit state=floating
bspc rule -a jetbrains-idea-ce state=floating
bspc rule -a "com.xunlei.download" state=floating
bspc rule -a ToDesk state=floating

bspc rule -a alacritty-float state=floating
bspc rule -a Gnome-screenshot state=floating
bspc rule -a st-256color state=floating
bspc rule -a Steam state=floating
